---
# tasks file for apache
- name: install apache package
  package: 
    name: httpd
    state=latest
  notify:
    - enable httpd
    - restart httpd
- name: change default page for apache
  shell: echo "<h1>Hello from {{publicip}}</h1>" > /var/www/html/index.html
  notify:
    - restart httpd
